<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_6125993f9cb6f',
	'title' => 'Informações sobre o curso:',
	'fields' => array(
		array(
			'key' => 'field_61297349dfd1d',
			'label' => 'Sobre o curso',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 1,
			'multi_expand' => 1,
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6129ac2e43a46',
			'label' => 'Modalidade do curso',
			'name' => 'modalidade_do_curso',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'formula' => '',
			'calculated_format' => '',
			'blank_if_zero' => 0,
			'readonly' => 0,
			'choices' => array(
				'Ao vivo' => 'Ao vivo',
				'Gravado' => 'Gravado',
				'E-Book' => 'E-Book',
                'Hibrido' => 'Hibrido',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_612cc791f5f2a',
			'label' => 'O curso é:',
			'name' => 'o_curso_e:',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6129ac2e43a46',
						'operator' => '!=',
						'value' => 'E-Book',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'formula' => '',
			'calculated_format' => '',
			'blank_if_zero' => 0,
			'readonly' => 0,
			'choices' => array(
				'Curso Pago' => 'Curso Pago',
				'Curso Gratuito' => 'Curso Gratuito',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_6127d261b719c',
			'label' => 'Carga horária',
			'name' => 'carga_horaria',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6129ac2e43a46',
						'operator' => '!=',
						'value' => 'E-Book',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'formula' => '',
			'calculated_format' => '',
			'blank_if_zero' => 0,
			'readonly' => 0,
			'default_value' => '',
			'placeholder' => 'Informe a carga horária do curso:',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6125998d1dccf',
			'label' => 'Público Alvo',
			'name' => 'Público Alvo',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6129ac2e43a46',
						'operator' => '!=',
						'value' => 'E-Book',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'formula' => '',
			'calculated_format' => '',
			'blank_if_zero' => 0,
			'readonly' => 0,
			'default_value' => '',
			'placeholder' => 'Descreva o público alvo:',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6129bd775ee86',
			'label' => 'Produto da Loja',
			'name' => 'produto',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_612cc791f5f2a',
						'operator' => '==',
						'value' => 'Curso Pago',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'formula' => '',
			'calculated_format' => '',
			'blank_if_zero' => 0,
			'readonly' => 0,
			'post_type' => array(
				0 => 'product',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 1,
			'return_format' => 'id',
			'ui' => 1,
		),
		array(
			'key' => 'field_61296f7360979',
			'label' => 'Data do Curso',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6129ac2e43a46',
						'operator' => '==',
						'value' => 'Ao vivo',
					),
				),
                array(
					array(
						'field' => 'field_6129ac2e43a46',
						'operator' => '==',
						'value' => 'Hibrido',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'formula' => '',
			'calculated_format' => '',
			'blank_if_zero' => 0,
			'readonly' => 0,
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6129b3e1fd55b',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'formula' => '',
			'calculated_format' => '',
			'blank_if_zero' => 0,
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_613ea4def7066',
			'label' => 'Hora',
			'name' => 'hora',
			'type' => 'time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'formula' => '',
			'calculated_format' => '',
			'blank_if_zero' => 0,
			'readonly' => 0,
			'display_format' => 'g:i a',
			'return_format' => 'H:i:s',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'portfolio',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'discussion',
		1 => 'slug',
		2 => 'page_attributes',
		3 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

endif;